language: java
dist: trusty
sudo: required
branches:
  only:
  - gh-pages
  - /.*/
install: "pip install -r requirements.txt"
#building and running the benchmarks
script:
- mvn clean install -f projan/pom.xml
- java -jar projan/target/projan-0.0.1-SNAPSHOT.jar com.testjan.projan.MyBenchmark.testRef -i 10 -rf csv -rff refBench
- java -jar projan/target/projan-0.0.1-SNAPSHOT.jar com.testjan.projan.MyBenchmark.testTenDot -i 10 -rf csv -rff testTen
#don't want an email every time I commit
notifications:
  email: false
after_success:
#installing the required packages for the python script to run
#- python -V
#- sudo apt-get update
#- sudo apt-get install -y python2.7
#- sudo apt-get install -y python-numpy
#- easy_install numpy
#- easy_install matplotlib
#- sudo apt-get install -y python-matplotlib
#- python -V
- chmod +x projan/update-gh.sh 
#pushes back to github the graph and the results
- ./projan/update-gh.sh
