language: java
dist: trusty
sudo: false
branches:
  only:
  - gh-pages
install: "pip install -r requirements.txt"
#building and running the benchmarks
script:
- mvn clean install -f projan/pom.xml
- java -jar projan/target/projan-0.0.1-SNAPSHOT.jar com.testjan.projan.MyBenchmarkMult.testRef -i 20 -rf csv -rff refBench
- java -jar projan/target/projan-0.0.1-SNAPSHOT.jar com.testjan.projan.MyBenchmarkAdd.testAddOrig -i 10 -p S=10,15,20,25,30,35,40,45,50,55,60 -rf csv -rff testAddOrig
- java -jar projan/target/projan-0.0.1-SNAPSHOT.jar com.testjan.projan.MyBenchmarkAdd.addMine -i 10 -p S=10,15,20,25,30,35,40,45,50,55,60 -rf csv -rff testAddMine
- java -jar projan/target/projan-0.0.1-SNAPSHOT.jar com.testjan.projan.MyBenchmarkAdd.testAddTransposeOrig -i 10 -p S=10,15,20,25,30,35,40,45,50,55,60 -rf csv -rff testAddTransposeOrig
- java -jar projan/target/projan-0.0.1-SNAPSHOT.jar com.testjan.projan.MyBenchmarkAdd.testAddTransposeMine -i 10 -p S=10,15,20,25,30,35,40,45,50,55,60 -rf csv -rff testAddTransposeMine
#don't want an email every time I commit
notifications:
  email: false
after_success:
- chmod +x projan/update-gh.sh 
#pushes back to github the graph and the results
- ./projan/update-gh.sh
